//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet4sitter.Resources.Recursos_Localizable {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmFiltrador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmFiltrador() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pet4sitter.Resources.Recursos_Localizable.FrmFiltrador", typeof(FrmFiltrador).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string btnBorrar_Text {
            get {
                return ResourceManager.GetString("btnBorrar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        internal static string btnBuscar_Text {
            get {
                return ResourceManager.GetString("btnBuscar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string button1_Text {
            get {
                return ResourceManager.GetString("button1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Distance.
        /// </summary>
        internal static string cmbDistancia_Text {
            get {
                return ResourceManager.GetString("cmbDistancia_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ascending.
        /// </summary>
        internal static string cmbDistanciaAscDesc_Text {
            get {
                return ResourceManager.GetString("cmbDistanciaAscDesc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Price.
        /// </summary>
        internal static string cmbOrdenarPrecio_Text {
            get {
                return ResourceManager.GetString("cmbOrdenarPrecio_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ascending.
        /// </summary>
        internal static string cmbPrecioAscDesc_Text {
            get {
                return ResourceManager.GetString("cmbPrecioAscDesc_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string label9_Text {
            get {
                return ResourceManager.GetString("label9_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a From:.
        /// </summary>
        internal static string lblDesde_Text {
            get {
                return ResourceManager.GetString("lblDesde_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Filters:.
        /// </summary>
        internal static string lblFiltros_Text {
            get {
                return ResourceManager.GetString("lblFiltros_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To:.
        /// </summary>
        internal static string lblHasta_Text {
            get {
                return ResourceManager.GetString("lblHasta_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort by Distance:.
        /// </summary>
        internal static string lblOrdenarPorDistancia_Text {
            get {
                return ResourceManager.GetString("lblOrdenarPorDistancia_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sort by Price:.
        /// </summary>
        internal static string lblOrdenarPrecio_Text {
            get {
                return ResourceManager.GetString("lblOrdenarPrecio_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Range:.
        /// </summary>
        internal static string lblRango_Text {
            get {
                return ResourceManager.GetString("lblRango_Text", resourceCulture);
            }
        }
    }
}
