//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pet4sitter.Resources.Recursos_Localizable {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FrmResultadoFiltrado {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrmResultadoFiltrado() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pet4sitter.Resources.Recursos_Localizable.FrmResultadoFiltrado", typeof(FrmResultadoFiltrado).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string btnAnterior_Text {
            get {
                return ResourceManager.GetString("btnAnterior_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mensaje.
        /// </summary>
        internal static string btnEnviarMensajeChat1_Text {
            get {
                return ResourceManager.GetString("btnEnviarMensajeChat1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mensaje.
        /// </summary>
        internal static string btnEnviarMensajeChat2_Text {
            get {
                return ResourceManager.GetString("btnEnviarMensajeChat2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mensaje.
        /// </summary>
        internal static string btnEnviarMensajeChat3_Text {
            get {
                return ResourceManager.GetString("btnEnviarMensajeChat3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string btnSiguiente_Text {
            get {
                return ResourceManager.GetString("btnSiguiente_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados.
        /// </summary>
        internal static string lblNombreCuidador1_Text {
            get {
                return ResourceManager.GetString("lblNombreCuidador1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados.
        /// </summary>
        internal static string lblNombreCuidador2_Text {
            get {
                return ResourceManager.GetString("lblNombreCuidador2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin resultados.
        /// </summary>
        internal static string lblNombreCuidador3_Text {
            get {
                return ResourceManager.GetString("lblNombreCuidador3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pagina x de x.
        /// </summary>
        internal static string lblPaginaActual_Text {
            get {
                return ResourceManager.GetString("lblPaginaActual_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecio1_Text {
            get {
                return ResourceManager.GetString("lblPrecio1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecio2_Text {
            get {
                return ResourceManager.GetString("lblPrecio2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Precio:.
        /// </summary>
        internal static string lblPrecio3_Text {
            get {
                return ResourceManager.GetString("lblPrecio3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xx.
        /// </summary>
        internal static string lblResPrecio1_Text {
            get {
                return ResourceManager.GetString("lblResPrecio1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xx.
        /// </summary>
        internal static string lblResPrecio2_Text {
            get {
                return ResourceManager.GetString("lblResPrecio2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a xx.
        /// </summary>
        internal static string lblResPrecio3_Text {
            get {
                return ResourceManager.GetString("lblResPrecio3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación:.
        /// </summary>
        internal static string lblUbicacion1_Text {
            get {
                return ResourceManager.GetString("lblUbicacion1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación:.
        /// </summary>
        internal static string lblUbicacion2_Text {
            get {
                return ResourceManager.GetString("lblUbicacion2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación:.
        /// </summary>
        internal static string lblUbicacion3_Text {
            get {
                return ResourceManager.GetString("lblUbicacion3_Text", resourceCulture);
            }
        }
    }
}
