; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Pet4Sitter"
#define MyAppVersion "1.0"
#define MyAppPublisher "Pet4Sitter Inc."
#define MyAppURL "http://100.27.120.128/"
#define MyAppExeName "pet4sitter.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{8C872E9F-474D-4DE7-AEC0-CCDEE6F7CEC1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Users\rngir\Desktop
OutputBaseFilename=mysetupsssss
SetupIconFile=C:\repos\piRojo\src\lgo.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\repos\piRojo\src\bin\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\BCrypt.Net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\BCrypt.Net.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\BouncyCastle.Cryptography.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\BouncyCastle.Cryptography.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\EntityFramework.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\EntityFramework.SqlServer.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\EntityFramework.SqlServer.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\EntityFramework.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\GMap.NET.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Auth.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Auth.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Auth.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Core.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Core.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Oauth2.v2.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Oauth2.v2.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.Oauth2.v2.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Apis.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Protobuf.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Protobuf.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Google.Protobuf.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Compression.LZ4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Compression.LZ4.Streams.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Compression.LZ4.Streams.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Compression.LZ4.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Hash.xxHash.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\K4os.Hash.xxHash.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Bcl.AsyncInterfaces.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Bcl.AsyncInterfaces.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.Binder.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.Binder.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Configuration.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.DependencyInjection.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Http.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Http.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Logging.Abstractions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Logging.Abstractions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Logging.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Logging.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Options.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Options.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Primitives.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Microsoft.Extensions.Primitives.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\MySql.Data.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\MySql.Data.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\NewsAPI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Newtonsoft.Json.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Newtonsoft.Json.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\OpenAI_API.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\OpenAI_API.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\pet4sitter.application"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\pet4sitter.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\pet4sitter.exe.config"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\pet4sitter.exe.manifest"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\pet4sitter.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Stripe.net.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\Stripe.net.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Buffers.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Buffers.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.CodeDom.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.CodeDom.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SqlClient.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SqlClient.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SQLite.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SQLite.EF6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SQLite.Linq.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Data.SQLite.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Diagnostics.DiagnosticSource.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Diagnostics.DiagnosticSource.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.IO.Pipelines.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.IO.Pipelines.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Memory.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Memory.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Numerics.Vectors.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Numerics.Vectors.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Runtime.CompilerServices.Unsafe.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Security.Principal.Windows.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Security.Principal.Windows.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\System.Threading.Tasks.Extensions.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\ZstdSharp.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\repos\piRojo\src\bin\Release\en-US\pet4sitter.resources.dll"; DestDir: "{app}\en-US"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

